# Start of script
# BluPhone Windows 10 sound settings
print ("Sound")
print ("\nBlocked sound\n")
print ("Repeat blocked sound [Unable to open]")
print ("Blocked sound by bit [Unable to open]")
print ("Blocked sound by kilobit [Unable to open]")
print ("Blocked sound by megabit [Unable to open]")
print ("Blocked sound by gigabit [Unable to open]")
print ("Blocked sound by terabit [Unable to open]")
print ("\nSound test\n")
print ("Front left [Unable to open]")
print ("Front right [Unable to open]")
print ("Back left [Unable to open]")
print ("Back right [Unable to open]")
print ("\nQuality\n")
print ("Current quality [Unable to open]")
print ("MIDI mode [Unable to open]")
print ("4 bit mode [Unable to open]")
print ("6 bit mode [Unable to open]")
print ("8 bit mode [Unable to open]")
print ("12 bit mode [Unable to open]")
print ("16 bit mode [Unable to open]")
print ("18 bit mode [Unable to open]")
print ("20 bit node [Unable to open]")
print ("24 bit mode [Unable to open]")
print ("28 bit mode [Unable to open]")
print ("32 bit mode [Unable to open]")
print ("36 bit mode [Unable to open]")
print ("42 bit mode [Unable to open]")
print ("48 bit mode [Unable to open]")
print ("54 bit mode [Unable to open]")
print ("64 bit mode [Unable to open]")
print ("\nAudio types\n")
print ("OGG [Unable to open]")
print ("MP3 [Unable to open]")
print ("ALAC [Unable to open]")
print ("FLAC [Unable to open]")
print ("WAV [Unable to open]")
print ("MID [Unable to open]")
print ("MP2 [Unable to open]")
print ("AIFF [Unable to open]")
print ("AAC [Unable to open]")
print ("M4A [Unable to open]")
print ("Other [Unable to open]")
print ("\nWaves\n")
print ("View soundwaves [Unable to open]")
print ("Hide soundwaves [Unable to open]")
noMore = input("Press [ENTER] key to exit current tab")
print ("This window should be closed now")
"""
I don't know enough about Python yet to make a functional GUI or to make these options openable
"""
'''
File info
File version: 1 (Friday, October 30th 2020 at 11:00 am)
File type: Python script file (*.py)
Line count (including blank lines and compiler line): 62
'''
# End of script
